import type { Product } from "@/lib/types";

// This file is no longer in use, but is kept for reference.
// Products are now fetched from Firestore.
export const products: Product[] = [
  {
    id: "1",
    name: "Mealie Meal (25kg)",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bag of Zambian mealie meal",
    shortDescription: "Roller meal for making nshima.",
    fullDescription: "A 25kg bag of fine roller meal, a staple food in Zambia used to make nshima. This is a must-have for every Zambian household.",
    price: 180.00,
    variations: [
      { name: "25kg Bag", priceModifier: 0 },
      { name: "10kg Bag", priceModifier: -100.00 },
    ],
    category: "Staples",
    dataAiHint: "mealie meal bag",
  },
  {
    id: "2",
    name: "Kapenta (Siavonga)",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bowl of dried kapenta",
    shortDescription: "Dried freshwater fish.",
    fullDescription: "A medium-sized bag of dried Kapenta from Siavonga. A popular and delicious source of protein, perfect for relishes.",
    price: 50.00,
    variations: [
      { name: "Medium Bag", priceModifier: 0 },
      { name: "Large Bag", priceModifier: 50.00 },
    ],
    category: "Protein",
    dataAiHint: "dried fish",
  },
  {
    id: "3",
    name: "Fresh Tomatoes",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A pile of fresh tomatoes",
    shortDescription: "Juicy, locally grown tomatoes.",
    fullDescription: "A kilogram of fresh, ripe tomatoes sourced from local farms. Essential for making any Zambian relish or salad.",
    price: 15.00,
    variations: [
      { name: "Per Kg", priceModifier: 0 },
    ],
    category: "Vegetables",
    dataAiHint: "tomatoes vegetable",
  },
  {
    id: "4",
    name: "Impwa",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bunch of impwa",
    shortDescription: "Fresh Zambian eggplants.",
    fullDescription: "A bunch of fresh Impwa, also known as Zambian eggplant. A key ingredient in many traditional dishes, loved for its unique bitter taste.",
    price: 10.00,
    variations: [
        { name: "Bunch", priceModifier: 0 },
    ],
    category: "Vegetables",
    dataAiHint: "african eggplant",
  },
  {
    id: "5",
    name: "Cooking Oil",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bottle of cooking oil",
    shortDescription: "Pure vegetable cooking oil.",
    fullDescription: "A 2.5-liter bottle of pure vegetable cooking oil, perfect for all your frying and cooking needs. An essential in every kitchen.",
    price: 95.00,
    variations: [
      { name: "2.5 Litre", priceModifier: 0 },
      { name: "5 Litre", priceModifier: 90.00 },
    ],
    category: "Pantry",
    dataAiHint: "cooking oil bottle",
  },
  {
    id: "6",
    name: "Chibwabwa",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bunch of pumpkin leaves",
    shortDescription: "Fresh pumpkin leaves.",
    fullDescription: "A fresh bunch of Chibwabwa (pumpkin leaves). Often cooked with groundnuts to make a delicious and nutritious relish.",
    price: 8.00,
    variations: [
      { name: "Bunch", priceModifier: 0 },
    ],
    category: "Vegetables",
    dataAiHint: "pumpkin leaves",
  },
  {
    id: "7",
    name: "Groundnuts",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bowl of groundnuts",
    shortDescription: "Raw, shelled groundnuts.",
    fullDescription: "A bag of raw, shelled groundnuts. Can be roasted for a snack or pounded into a powder for use in traditional dishes like Ifisashi.",
    price: 25.00,
    variations: [
      { name: "500g Bag", priceModifier: 0 },
      { name: "1kg Bag", priceModifier: 20.00 },
    ],
    category: "Pantry",
    dataAiHint: "peanuts shelled",
  },
  {
    id: "8",
    name: "Sunlight Soap",
    image: "https://placehold.co/400x400.png",
    imageAlt: "A bar of Sunlight soap",
    shortDescription: "Multipurpose green bar soap.",
    fullDescription: "The classic green bar of Sunlight soap. A multipurpose soap trusted by generations for laundry, dishwashing, and general cleaning.",
    price: 18.00,
    variations: [
        { name: "Single Bar", priceModifier: 0 },
    ],
    category: "Household",
    dataAiHint: "bar soap",
  },
];
